name: Notify GitHub contributions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'
    - cron: '0 14 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17.6'
    - run: go version

    - name: Setup .gngc.toml
      run: |
        pwd
        echo $HOME
        echo -=-=-=-=-=-=
        cd /home/runner/work/gngc/gngc/config
        cat << EOF > config.toml
        [GitHub]
        Token=hoge
        UserName=hoge

        [IFTTT]
        EventName=hoge
        Token=hoge
        EOF
        ls
        cat config.toml

    - name: Run main.go
      run: |
        go run main.go -n --config /home/runner/work/gngc/gngc/config/config.toml
        echo ----------
        go run main.go -n 
