name: Notify GitHub contributions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'
    - cron: '0 14 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17.6'
    - run: go version
    
    - name: Setup .gngc.toml
      run: |
        pwd
        echo $HOME
        echo -=-=-=-=-=-=
        cat << EOF > /home/runner/work/gngc/gngc/config/config.toml
        [hoge]
        Token = ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        UserName = ${{ secrets.USER_NAME }}

        [IFTTT]
        EventName = ${{ secrets.IFTTT_EVENT_NAME }}
        Token = ${{ secrets.IFTTT_TOKEN }}
        EOF
        ls

    - name: Run main.go
      run: |
        go run main.go -n --config /home/runner/work/gngc/gngc/config/config.toml
