name: Notify GitHub contributions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'
    - cron: '0 14 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17.6'
    - run: go version

    - name: Setup .gngc.toml
      run: |
        cat << EOF > $HOME/.gngc.toml
        [GitHub]
        Token="${{ secrets.PERSONAL_ACCESS_TOKEN }}"
        UserName="${{ secrets.USER_NAME }}"

        [IFTTT]
        EventName="${{ secrets.IFTTT_EVENT_NAME }}"
        Token="${{ secrets.IFTTT_TOKEN }}"
        EOF

    - name: Run main.go
      run: |
        go run main.go -n 

    - name: Delete .gngc.toml
      run: |
        rm $HOME/.gngc.toml
