name: Notify GitHub contributions

on:
  push:
    branches: [ main ]
    paths:
      - 'gngc/**'
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'
    - cron: '0 14 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .env
      run: |
        pwd
        ls
        echo ------
        cd /home/runner/work/gngc
        cat << EOF > .env
        IFTTT_TOKEN=${{ secrets.IFTTT_TOKEN }}
        USER_NAME=${{ secrets.USER_NAME }}
        API_TOKEN=${{ secrets.API_TOKEN }}
        EOF

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.6'
      - run: go version

      - name: Run main.go
        run: |
          cd scripts
          go run main.go

    - name: Delete .env
      run: |
        cd /home/runner/work/gngc
        rm .env
